<?xml version="1.0"?>
<package format="3">
  <name>robot_bringup</name>
  <version>0.1.0</version>
  <description>任务系统的中文配置和模拟、实机启动入口</description>
  <maintainer email="team2@example.invalid">DASE7503 第二队</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>mission_manager</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
